apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ztrlr3m2g-nodejs
  janus-idp.io/tekton: ztrlr3m2g-nodejs
  backstage.io/kubernetes-id: ztrlr3m2g-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ztrlr3m2g-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
